"""Added price to sneakers.

Revision ID: 23556d144acf
Revises: dbdd67c20260
Create Date: 2023-08-28 17:38:54.556836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23556d144acf'
down_revision: Union[str, None] = 'dbdd67c20260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sneakers', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sneakers', 'price')
    # ### end Alembic commands ###
