"""Create SneakerBrand model

Revision ID: 909e6b1fb95c
Revises: 69d13e27c695
Create Date: 2023-08-17 22:32:04.273135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909e6b1fb95c'
down_revision: Union[str, None] = '69d13e27c695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sneaker_Brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sneaker_Brand',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sneaker_Brand_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'name', name='Sneaker_Brand_pkey')
    )
    # ### end Alembic commands ###
