"""Create SneakerBrand model

Revision ID: b90bce6e75c7
Revises: 909e6b1fb95c
Create Date: 2023-08-17 22:35:13.326757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90bce6e75c7'
down_revision: Union[str, None] = '909e6b1fb95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
